# -*- encoding: utf-8 -*-
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 21:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20160325_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 25, 21, 36, 32, 951449, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
