# -*- encoding: utf-8 -*-
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_auto_20160325_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operation',
            field=models.IntegerField(choices=[(0, 'Deposit'), (1, 'Withdraw')]),
        ),
    ]
