version: '2'
services:
    django:
        build:
            context: .
            dockerfile: ./docker_files/django/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        stdin_open: true
        tty: true
        volumes:
            - .:/django
        ports:
            - "8000:8000"
        links:
            - database
            #- webapp
        environment:
            DEBUG: "true"
            # default database
            DATABASE_NAME: django
            DATABASE_USER: django
            DATABASE_PASSWORD: django
            DATABASE_SERVICE_HOST: database
            # test database
            DATABASE_NAME_TEST: django_test
    database:
        image: postgres:latest
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: django
volumes:
    pgdata: {}
