version: '2'
services:

    python:
        build: .
        environment:
            DEBUG: 'true'
            PORT: '8080'
        #volumes:
        #  - ./:/app:rw
        ports:
          - "8080:8080"
        links:
            - mongodb:database

    mongodb:
        image: mvertes/alpine-mongo:3.2.3
        restart: unless-stopped
        ports:
            - "27017:27017"

    mongo-seed:
        build: ./mongo-seed
        links:
            - mongodb
        environment:
            - MONGO_HOST=mongodb
