# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana', '0004_auto_20160509_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
